name: CI

on:
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: "Install Dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/install
  lint:
    name: "Lint"
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/install
      - run: yarn lint
  test:
    name: "Test"
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/install
      - run: yarn test:ember
